openapi: 3.0.3
info:
    title: api
    version: 0.1.0

paths:
    '/nutrients':
        $ref: 'nutrients.yaml#/paths/~1nutrients'

    '/nutrients/{NutrientId}':
        $ref: 'nutrients.yaml#/paths/~1nutrients~1{id}'
