openapi: 3.0.3
info:
  title: api
  version: 0.1.0

paths:
  /nutrients:
    get:
      tags: [nutrients]
      operationId: listNutrients
      summary: Lista witamin
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema: { $ref: '#/components/schemas/NutrientsList' }

components:
  schemas:
    NutrientsList:
      type: array
      items: { $ref: '#/components/schemas/NutrientListItem' }

    NutrientListItem:
      type: object
      required: [id, name]
      properties:
        id: {type: integer}
        name: { type: string }