create table if not exists nutrient
(
    id   smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE
);

create table if not exists ingredient
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE
);

CREATE TABLE ingredient_nutrient
(
    ingredient_id BIGINT NOT NULL REFERENCES ingredient (id) ON DELETE CASCADE,
    nutrient_id   BIGINT NOT NULL REFERENCES nutrient (id) ON DELETE CASCADE,
    PRIMARY KEY (ingredient_id, nutrient_id)
);