CREATE TABLE IF NOT EXISTS app_user (
                                        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        email       TEXT    NOT NULL UNIQUE,
                                        name        TEXT    NOT NULL,
                                        created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    );