create table if not exists nutrient
(
    id   smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE
);

create table if not exists ingredient
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE
);

CREATE TABLE if not exists ingredient_nutrient
(
    ingredient_id smallint NOT NULL REFERENCES ingredient (id) ON DELETE CASCADE,
    nutrient_id   BIGINT NOT NULL REFERENCES nutrient (id) ON DELETE CASCADE,
    amount smallint NOT NULL,
    unit text NOT NULL UNIQUE,
    PRIMARY KEY (ingredient_id, nutrient_id)
);