create table if not exists diet_app.recipe
(
    id    bigint generated by default as identity primary key,
    name  text  not null,
    steps jsonb not null
);

create table if not exists diet_app.recipe_ingredient
(
    recipe_id     bigint         not null references recipe (id) on delete cascade,
    ingredient_id bigint         not null references ingredient (id) on delete cascade,
    amount        numeric(11, 3) not null,
    primary key (recipe_id, ingredient_id)
);