create table if not exists nutrient
(
    id   smallint generated by default as identity primary key,
    name text not null unique,
    unit text not null
);

create table if not exists ingredient
(
    id   INTEGER generated by default as identity primary key,
    name text not null unique
);

create table if not exists ingredient_nutrient
(
    ingredient_id smallint not null references ingredient (id) on delete cascade,
    nutrient_id   BIGINT   not null references nutrient (id) on delete cascade,
    amount        smallint not null,
    primary key (ingredient_id, nutrient_id)
);