package pl.edu.pjwstk.s25236.dietapp.bls

import pl.edu.pjwstk.s25236.dietapp.processing.removeBracketContent
import java.math.BigDecimal

data class BlsIngredientDto(
    val nameDe: String,
    val nameEn: String,
    val energyKj: BigDecimal,
    val energyKcl: BigDecimal,
    val water: BigDecimal,
    val protein: BigDecimal,
    val fat: BigDecimal,
    val carbohydrateAvailable: BigDecimal,
    val fibreDietaryTotal: BigDecimal,
    val alcohol: BigDecimal,
    val organicAcidsTotal: BigDecimal,
    val ash: BigDecimal,
    val vitaminARetinolEquivalents: BigDecimal,
    val vitaminARetinolActivityEquivalents: BigDecimal,
    val retinol: BigDecimal,
    val betaCarotene: BigDecimal,
    val carotenoidsExcludingBetaCarotene: BigDecimal,
    val vitaminD: BigDecimal,
    val vitaminD3: BigDecimal,
    val vitaminD2: BigDecimal,
    val vitaminE: BigDecimal,
    val alphaTocopherol: BigDecimal,
    val betaTocopherol: BigDecimal,
    val gammaTocopherol: BigDecimal,
    val deltaTocopherol: BigDecimal,
    val alphaTocotrienol: BigDecimal,
    val vitaminK: BigDecimal,
    val vitaminK1: BigDecimal,
    val vitaminK2: BigDecimal,
    val vitaminB1: BigDecimal,
    val vitaminB2: BigDecimal,
    val niacinEquivalents: BigDecimal,
    val niacin: BigDecimal,
    val pantothenicAcid: BigDecimal,
    val vitaminB6: BigDecimal,
    val biotin: BigDecimal,
    val folateEquivalent: BigDecimal,
    val folate: BigDecimal,
    val folicAcidSynthetic: BigDecimal,
    val vitaminB12: BigDecimal,
    val vitaminC: BigDecimal,
    val salt: BigDecimal,
    val sodium: BigDecimal,
    val chloride: BigDecimal,
    val potassium: BigDecimal,
    val calcium: BigDecimal,
    val magnesium: BigDecimal,
    val phosphorus: BigDecimal,
    val sulphur: BigDecimal,
    val iron: BigDecimal,
    val zinc: BigDecimal,
    val iodide: BigDecimal,
    val copper: BigDecimal,
    val manganese: BigDecimal,
    val fluoride: BigDecimal,
    val chromium: BigDecimal,
    val molybdenum: BigDecimal,
    val aceticAcid: BigDecimal,
    val citricAcid: BigDecimal,
    val lacticAcid: BigDecimal,
    val malicAcid: BigDecimal,
    val tartaricAcid: BigDecimal,
    val polyolsTotal: BigDecimal,
    val mannitol: BigDecimal,
    val sorbitol: BigDecimal,
    val xylitol: BigDecimal,
    val monosaccharidesTotal: BigDecimal,
    val glucose: BigDecimal,
    val fructose: BigDecimal,
    val galactose: BigDecimal,
    val disaccharidesTotal: BigDecimal,
    val sucrose: BigDecimal,
    val maltose: BigDecimal,
    val lactose: BigDecimal,
    val sugarsTotal: BigDecimal,
    val oligosaccharidesAvailable: BigDecimal,
    val starch: BigDecimal,
    val fibreLowMolecularWeight: BigDecimal,
    val fibreHighMolecularWeight: BigDecimal,
    val fibreWaterInsoluble: BigDecimal,
    val fibreWaterSoluble: BigDecimal,
    val fibreHighMolecularWeightWaterSoluble: BigDecimal,
    val fibreHighMolecularWeightWaterInsoluble: BigDecimal,
    val fattyAcidsSaturatedTotal: BigDecimal,
    val fattyAcidC40: BigDecimal,
    val fattyAcidC60: BigDecimal,
    val fattyAcidC80: BigDecimal,
    val fattyAcidC100: BigDecimal,
    val fattyAcidC120: BigDecimal,
    val fattyAcidC140: BigDecimal,
    val fattyAcidC150: BigDecimal,
    val fattyAcidC160: BigDecimal,
    val fattyAcidC170: BigDecimal,
    val fattyAcidC180: BigDecimal,
    val fattyAcidC200: BigDecimal,
    val fattyAcidC220: BigDecimal,
    val fattyAcidC240: BigDecimal,
    val fattyAcidsMonounsaturatedTotal: BigDecimal,
    val fattyAcidC141N5Cis: BigDecimal,
    val fattyAcidC161N7Cis: BigDecimal,
    val fattyAcidC181N7Cis: BigDecimal,
    val fattyAcidC181N9Cis: BigDecimal,
    val fattyAcidC201N9Cis: BigDecimal,
    val fattyAcidC221N9Cis: BigDecimal,
    val fattyAcidsPolyunsaturatedTotal: BigDecimal,
    val fattyAcidsPolyunsaturatedN3Total: BigDecimal,
    val fattyAcidC183N3AllCis: BigDecimal,
    val fattyAcidC184N3AllCis: BigDecimal,
    val fattyAcidC205N3AllCis: BigDecimal,
    val fattyAcidC225N3AllCis: BigDecimal,
    val fattyAcidC226N3AllCis: BigDecimal,
    val fattyAcidsPolyunsaturatedN6Total: BigDecimal,
    val fattyAcidC182N6Ciscis: BigDecimal,
    val fattyAcidC182ConjugatedCis9Trans11: BigDecimal,
    val fattyAcidC183N6AllCis: BigDecimal,
    val fattyAcidC202N6Ciscis: BigDecimal,
    val fattyAcidC203N6AllCis: BigDecimal,
    val fattyAcidC204N6AllCis: BigDecimal,
    val fattyAcidsOthers: BigDecimal,
    val cholesterol: BigDecimal,
    val aminoAcidsEssentialTotal: BigDecimal,
    val alanine: BigDecimal,
    val arginine: BigDecimal,
    val asparticAcidIncludingAsparagine: BigDecimal,
    val cysteine: BigDecimal,
    val glutamicAcidIncludingGlutamine: BigDecimal,
    val glycine: BigDecimal,
    val histidine: BigDecimal,
    val isoleucine: BigDecimal,
    val leucine: BigDecimal,
    val lysine: BigDecimal,
    val methionine: BigDecimal,
    val phenylalanine: BigDecimal,
    val proline: BigDecimal,
    val serine: BigDecimal,
    val threonine: BigDecimal,
    val tryptophan: BigDecimal,
    val tyrosine: BigDecimal,
    val valine: BigDecimal,
    val nitrogenTotal: BigDecimal,
) {
    fun tokens(): List<String> =
        this.nameEn
            .removeBracketContent()
            .lowercase()
            .split(Regex("[^a-z0-9]+"))
            .map { it.trim() }
            .filter(String::isNotBlank)

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as BlsIngredientDto

        return nameEn == other.nameEn
    }

    override fun hashCode(): Int = nameEn.hashCode()
}
